# Exploratory data analysis

The goal of this notebook is to profile the data and see if any data cleaning or pre processing steps are required.

## Bronze to Silver - Data cleaning and basic pre-processing

Core idea of this layer: adress all the potential issues flagged by the data profiling library.

In [1]:
import os
import sys
import time
sys.path.append("..")

import pandas as pd
import polars as pl
from data_profiling import ProfileReport
from ingest import get_engine

/Users/aleksandrmedvedev/Desktop/Repositories/olist_project/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
engine = get_engine()

print("Waking up Azure SQL...")
for attempt in range(1, 11):
    try:
        with engine.connect() as conn:
            conn.exec_driver_sql("SELECT 1")
        print("Database is ready.")
        break
    except Exception:
        print(f"Attempt {attempt}/10 — retrying in 10s...")
        time.sleep(10)
else:
    raise RuntimeError("Database did not respond after 10 attempts.")

Waking up Azure SQL...
Attempt 1/10 — retrying in 10s...
Attempt 2/10 — retrying in 10s...
Database is ready.

In [3]:
customers            = pl.read_database("SELECT * FROM olist_customers_dataset", engine)
geolocation          = pl.read_database("SELECT * FROM olist_geolocation_dataset", engine)
order_items          = pl.read_database("SELECT * FROM olist_order_items_dataset", engine)
order_payments       = pl.read_database("SELECT * FROM olist_order_payments_dataset", engine)
order_reviews        = pl.read_database("SELECT * FROM olist_order_reviews_dataset", engine)
orders               = pl.read_database("SELECT * FROM olist_orders_dataset", engine)
products             = pl.read_database("SELECT * FROM olist_products_dataset", engine)
sellers              = pl.read_database("SELECT * FROM olist_sellers_dataset", engine)
category_translation = pl.read_database("SELECT * FROM product_category_name_translation", engine)

In [4]:
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation,
}

In [49]:
def generate_table_info(datasets, info_dir="info"):
    os.makedirs(info_dir, exist_ok=True)

    if os.listdir(info_dir):
        print(f"'{info_dir}' is not empty, skipping generation.")
        return

    tables_summary = []

    for name, df in datasets.items():
        lines = [
            f"Dataset: {name}",
            f"Shape: {df.shape[0]} rows x {df.shape[1]} columns",
            "Columns:",
            *(f"  - {col} ({dtype})" for col, dtype in zip(df.columns, df.dtypes)),
        ]
        content = "\n".join(lines)

        with open(f"{info_dir}/{name}.txt", "w") as f:
            f.write(content + "\n")

        tables_summary.append(content)
        print(f"Generated: {info_dir}/{name}.txt")

    with open(f"{info_dir}/tables.txt", "w") as f:
        f.write("\n\n".join(tables_summary) + "\n")

    print(f"Generated: {info_dir}/tables.txt")


generate_table_info(datasets)

'info' is not empty, skipping generation.

In [6]:
dataset_reports = {}

for name, df in datasets.items():
    report = ProfileReport(df.to_pandas(), title=f"{name} profiling report", minimal=True, progress_bar=False) # minimal generation does not account for duplicates 
    report.to_file(f"html_reports/{name}.html")
    dataset_reports[name] = report
    print(f"Generated: html_reports/{name}.html")

100%|██████████| 5/5 [00:00<00:00, 11.72it/s]

Generated: html_reports/customers.html

100%|██████████| 5/5 [00:00<00:00, 10.36it/s]

Generated: html_reports/geolocation.html

100%|██████████| 7/7 [00:00<00:00, 16.90it/s]

Generated: html_reports/order_items.html

100%|██████████| 5/5 [00:00<00:00, 16.99it/s]

Generated: html_reports/order_payments.html

100%|██████████| 7/7 [00:00<00:00, 10.67it/s]

Generated: html_reports/order_reviews.html

100%|██████████| 8/8 [00:01<00:00,  6.83it/s]

Generated: html_reports/orders.html

100%|██████████| 9/9 [00:00<00:00, 151.68it/s]

Generated: html_reports/products.html

100%|██████████| 4/4 [00:00<00:00, 657.05it/s]

Generated: html_reports/sellers.html

100%|██████████| 2/2 [00:00<00:00, 29433.71it/s]

Generated: html_reports/category_translation.html

## Pre processing pipelines

### Customers

Preprocessing: drop customer_unique_id column.

In [20]:
customers.shape

(99441, 5)

In [7]:
customers.head()

shape: (5, 5)
┌────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────┐
│ customer_id        ┆ customer_unique_id ┆ customer_zip_code ┆ customer_city     ┆ customer_state │
│ ---                ┆ ---                ┆ _prefix           ┆ ---               ┆ ---            │
│ str                ┆ str                ┆ ---               ┆ str               ┆ str            │
│                    ┆                    ┆ i64               ┆                   ┆                │
╞════════════════════╪════════════════════╪═══════════════════╪═══════════════════╪════════════════╡
│ 06b8999e2fba1a1fbc ┆ 861eff4711a542e4b9 ┆ 14409             ┆ franca            ┆ SP             │
│ 88172c00ba8b…      ┆ 3843c6dd7feb…      ┆                   ┆                   ┆                │
│ 18955e83d337fd6b2d ┆ 290c77bc529b7ac935 ┆ 9790              ┆ sao bernardo do   ┆ SP             │
│ ef6b18a428ac…      ┆ b93aa66c333d…      ┆                   ┆ campo             ┆                │
│ 4e7b3e00288586ebd0 ┆ 060e732b5b29e8181a ┆ 1151              ┆ sao paulo         ┆ SP             │
│ 8712fdd0374a…      ┆ 18229c7b0b2b…      ┆                   ┆                   ┆                │
│ b2b6027bc5c5109e52 ┆ 259dac757896d24d77 ┆ 8775              ┆ mogi das cruzes   ┆ SP             │
│ 9d4dc6358b12…      ┆ 02b9acbbff3f…      ┆                   ┆                   ┆                │
│ 4f2d8ab171c80ec836 ┆ 345ecd01c38d18a903 ┆ 13056             ┆ campinas          ┆ SP             │
│ 4f7c12e35b23…      ┆ 6ed96c73b8d0…      ┆                   ┆                   ┆                │
└────────────────────┴────────────────────┴───────────────────┴───────────────────┴────────────────┘

In [12]:
customers['customer_unique_id'].is_unique().all()

False

In [13]:
customers.describe()

shape: (9, 6)
┌────────────┬─────────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ statistic  ┆ customer_id     ┆ customer_uniqu ┆ customer_zip_c ┆ customer_city  ┆ customer_state │
│ ---        ┆ ---             ┆ e_id           ┆ ode_prefix     ┆ ---            ┆ ---            │
│ str        ┆ str             ┆ ---            ┆ ---            ┆ str            ┆ str            │
│            ┆                 ┆ str            ┆ f64            ┆                ┆                │
╞════════════╪═════════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ count      ┆ 99441           ┆ 99441          ┆ 99441.0        ┆ 99441          ┆ 99441          │
│ null_count ┆ 0               ┆ 0              ┆ 0.0            ┆ 0              ┆ 0              │
│ mean       ┆ null            ┆ null           ┆ 35137.474583   ┆ null           ┆ null           │
│ std        ┆ null            ┆ null           ┆ 29797.938996   ┆ null           ┆ null           │
│ min        ┆ 00012a2ce6f8dcd ┆ 0000366f3b9a79 ┆ 1003.0         ┆ abadia dos     ┆ AC             │
│            ┆ a20d059ce984917 ┆ 92bf8c76cfdf32 ┆                ┆ dourados       ┆                │
│            ┆ …               ┆ 21…            ┆                ┆                ┆                │
│ 25%        ┆ null            ┆ null           ┆ 11347.0        ┆ null           ┆ null           │
│ 50%        ┆ null            ┆ null           ┆ 24416.0        ┆ null           ┆ null           │
│ 75%        ┆ null            ┆ null           ┆ 58900.0        ┆ null           ┆ null           │
│ max        ┆ ffffe8b65bbe308 ┆ ffffd2657e2aad ┆ 99990.0        ┆ zortea         ┆ TO             │
│            ┆ 7b653a978c870db ┆ 2907e67c3e9dae ┆                ┆                ┆                │
│            ┆ …               ┆ cb…            ┆                ┆                ┆                │
└────────────┴─────────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

Since the customers_unique_id is actually not unique, we will drop this column.

In [ ]:
customers = customers.drop("customer_unique_id")

shape: (99_441, 4)
┌──────────────────────────────┬──────────────────────────┬───────────────────────┬────────────────┐
│ customer_id                  ┆ customer_zip_code_prefix ┆ customer_city         ┆ customer_state │
│ ---                          ┆ ---                      ┆ ---                   ┆ ---            │
│ str                          ┆ i64                      ┆ str                   ┆ str            │
╞══════════════════════════════╪══════════════════════════╪═══════════════════════╪════════════════╡
│ 06b8999e2fba1a1fbc88172c00ba ┆ 14409                    ┆ franca                ┆ SP             │
│ 8b…                          ┆                          ┆                       ┆                │
│ 18955e83d337fd6b2def6b18a428 ┆ 9790                     ┆ sao bernardo do campo ┆ SP             │
│ ac…                          ┆                          ┆                       ┆                │
│ 4e7b3e00288586ebd08712fdd037 ┆ 1151                     ┆ sao paulo             ┆ SP             │
│ 4a…                          ┆                          ┆                       ┆                │
│ b2b6027bc5c5109e529d4dc6358b ┆ 8775                     ┆ mogi das cruzes       ┆ SP             │
│ 12…                          ┆                          ┆                       ┆                │
│ 4f2d8ab171c80ec8364f7c12e35b ┆ 13056                    ┆ campinas              ┆ SP             │
│ 23…                          ┆                          ┆                       ┆                │
│ …                            ┆ …                        ┆ …                     ┆ …              │
│ 17ddf5dd5d51696bb3d7c6291687 ┆ 3937                     ┆ sao paulo             ┆ SP             │
│ be…                          ┆                          ┆                       ┆                │
│ e7b71a9017aa05c9a7fd292d7148 ┆ 6764                     ┆ taboao da serra       ┆ SP             │
│ 58…                          ┆                          ┆                       ┆                │
│ 5e28dfe12db7fb50a4b2f691faec ┆ 60115                    ┆ fortaleza             ┆ CE             │
│ ea…                          ┆                          ┆                       ┆                │
│ 56b18e2166679b8a959d72dd06da ┆ 92120                    ┆ canoas                ┆ RS             │
│ 27…                          ┆                          ┆                       ┆                │
│ 274fa6071e5e17fe303b97486410 ┆ 6703                     ┆ cotia                 ┆ SP             │
│ 82…                          ┆                          ┆                       ┆                │
└──────────────────────────────┴──────────────────────────┴───────────────────────┴────────────────┘

In [16]:
customers['customer_id'].is_unique().all()

True

### Geolocation

Pre-processing: grouping by the zip code to reduce duplicates.

Geolocation dataset has no unique column, although it is connected via a zip_code_prefix to the customers dataset. We want to make that column unique.

In [19]:
geolocation.shape

(1000163, 5)

In [17]:
geolocation.head()

shape: (5, 5)
┌───────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┐
│ geolocation_zip_code_ ┆ geolocation_lat ┆ geolocation_lng ┆ geolocation_city ┆ geolocation_state │
│ prefix                ┆ ---             ┆ ---             ┆ ---              ┆ ---               │
│ ---                   ┆ f64             ┆ f64             ┆ str              ┆ str               │
│ i64                   ┆                 ┆                 ┆                  ┆                   │
╞═══════════════════════╪═════════════════╪═════════════════╪══════════════════╪═══════════════════╡
│ 1037                  ┆ -23.545621      ┆ -46.639292      ┆ sao paulo        ┆ SP                │
│ 1046                  ┆ -23.546081      ┆ -46.64482       ┆ sao paulo        ┆ SP                │
│ 1046                  ┆ -23.546129      ┆ -46.642951      ┆ sao paulo        ┆ SP                │
│ 1041                  ┆ -23.544392      ┆ -46.639499      ┆ sao paulo        ┆ SP                │
│ 1035                  ┆ -23.541578      ┆ -46.641607      ┆ sao paulo        ┆ SP                │
└───────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┘

In [18]:
geolocation.null_count()

shape: (1, 5)
┌───────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┐
│ geolocation_zip_code_ ┆ geolocation_lat ┆ geolocation_lng ┆ geolocation_city ┆ geolocation_state │
│ prefix                ┆ ---             ┆ ---             ┆ ---              ┆ ---               │
│ ---                   ┆ u32             ┆ u32             ┆ u32              ┆ u32               │
│ u32                   ┆                 ┆                 ┆                  ┆                   │
╞═══════════════════════╪═════════════════╪═════════════════╪══════════════════╪═══════════════════╡
│ 0                     ┆ 0               ┆ 0               ┆ 0                ┆ 0                 │
└───────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┘

In [ ]:
geolocation = geolocation.group_by("geolocation_zip_code_prefix").agg(
    pl.col("geolocation_lat").mean(),
    pl.col("geolocation_lng").mean(),
    pl.col("geolocation_city").mode().first(),
    pl.col("geolocation_state").mode().first(),
)

geolocation

shape: (19_015, 5)
┌───────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┐
│ geolocation_zip_code_ ┆ geolocation_lat ┆ geolocation_lng ┆ geolocation_city ┆ geolocation_state │
│ prefix                ┆ ---             ┆ ---             ┆ ---              ┆ ---               │
│ ---                   ┆ f64             ┆ f64             ┆ str              ┆ str               │
│ i64                   ┆                 ┆                 ┆                  ┆                   │
╞═══════════════════════╪═════════════════╪═════════════════╪══════════════════╪═══════════════════╡
│ 50620                 ┆ -8.045357       ┆ -34.914544      ┆ recife           ┆ PE                │
│ 13157                 ┆ -22.63676       ┆ -47.198048      ┆ cosmopolis       ┆ SP                │
│ 29103                 ┆ -20.384654      ┆ -40.323728      ┆ vila velha       ┆ ES                │
│ 65030                 ┆ -2.544402       ┆ -44.28104       ┆ sao luis         ┆ MA                │
│ 3055                  ┆ -23.540582      ┆ -46.59939       ┆ sao paulo        ┆ SP                │
│ …                     ┆ …               ┆ …               ┆ …                ┆ …                 │
│ 88318                 ┆ -26.987472      ┆ -48.79356       ┆ itajai           ┆ SC                │
│ 68516                 ┆ -12.521264      ┆ -48.403494      ┆ parauapebas      ┆ PA                │
│ 92900                 ┆ -30.354614      ┆ -51.58423       ┆ mariana pimentel ┆ RS                │
│ 18206                 ┆ -23.617241      ┆ -48.058288      ┆ itapetininga     ┆ SP                │
│ 45850                 ┆ -16.088462      ┆ -39.614366      ┆ itagimirim       ┆ BA                │
└───────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┘

The aggregation reduced the dataset size from 1M rows to 19K! There were a lot of duplicates in the data, potentially the artifact of order processing.

In [25]:
geolocation["geolocation_zip_code_prefix"].is_unique().all()

True

In [27]:
geolocation = geolocation.sort("geolocation_zip_code_prefix", descending=False)

### Order items

Pre-processing: conversion to timestamp data

Order item id represents the position of an item within a basket. A single customer can order multiple items e.g 3, so then for that specific order_id we would have 3 order item id's.

In [28]:
order_items.head()

shape: (5, 7)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────┬──────────────┐
│ order_id      ┆ order_item_i ┆ product_id   ┆ seller_id    ┆ shipping_lim ┆ price ┆ freight_valu │
│ ---           ┆ d            ┆ ---          ┆ ---          ┆ it_date      ┆ ---   ┆ e            │
│ str           ┆ ---          ┆ str          ┆ str          ┆ ---          ┆ f64   ┆ ---          │
│               ┆ i64          ┆              ┆              ┆ str          ┆       ┆ f64          │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════╪══════════════╡
│ 00010242fe8c5 ┆ 1            ┆ 4244733e06e7 ┆ 48436dade18a ┆ 2017-09-19   ┆ 58.9  ┆ 13.29        │
│ a6d1ba2dd792c ┆              ┆ ecb4970a6e26 ┆ c8b2bce089ec ┆ 09:45:35     ┆       ┆              │
│ b162…         ┆              ┆ 83c13e…      ┆ 2a0412…      ┆              ┆       ┆              │
│ 00018f77f2f03 ┆ 1            ┆ e5f2d52b8021 ┆ dd7ddc04e1b6 ┆ 2017-05-03   ┆ 239.9 ┆ 19.93        │
│ 20c557190d7a1 ┆              ┆ 89ee658865ca ┆ c2c614352b38 ┆ 11:05:13     ┆       ┆              │
│ 44bd…         ┆              ┆ 93d83a…      ┆ 3efe2d…      ┆              ┆       ┆              │
│ 000229ec39822 ┆ 1            ┆ c777355d18b7 ┆ 5b51032eddd2 ┆ 2018-01-18   ┆ 199.0 ┆ 17.87        │
│ 4ef6ca0657da4 ┆              ┆ 2b67abbeef9d ┆ 42adc84c38ac ┆ 14:48:30     ┆       ┆              │
│ fc70…         ┆              ┆ f44fd0…      ┆ ab88f2…      ┆              ┆       ┆              │
│ 00024acbcdf0a ┆ 1            ┆ 7634da152a46 ┆ 9d7a1d34a505 ┆ 2018-08-15   ┆ 12.99 ┆ 12.79        │
│ 6daa1e931b038 ┆              ┆ 10f1595efa32 ┆ 240900642527 ┆ 10:10:18     ┆       ┆              │
│ 114c…         ┆              ┆ f14722…      ┆ 5ba1c2…      ┆              ┆       ┆              │
│ 00042b26cf59d ┆ 1            ┆ ac6c3623068f ┆ df560393f3a5 ┆ 2017-02-13   ┆ 199.9 ┆ 18.14        │
│ 7ce69dfabb4e5 ┆              ┆ 30de03045865 ┆ 1e74553ab940 ┆ 13:57:51     ┆       ┆              │
│ 5b4f…         ┆              ┆ e4e100…      ┆ 04ba5c…      ┆              ┆       ┆              │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────┴──────────────┘

In [29]:
order_items.null_count()

shape: (1, 7)
┌──────────┬───────────────┬────────────┬───────────┬─────────────────────┬───────┬───────────────┐
│ order_id ┆ order_item_id ┆ product_id ┆ seller_id ┆ shipping_limit_date ┆ price ┆ freight_value │
│ ---      ┆ ---           ┆ ---        ┆ ---       ┆ ---                 ┆ ---   ┆ ---           │
│ u32      ┆ u32           ┆ u32        ┆ u32       ┆ u32                 ┆ u32   ┆ u32           │
╞══════════╪═══════════════╪════════════╪═══════════╪═════════════════════╪═══════╪═══════════════╡
│ 0        ┆ 0             ┆ 0          ┆ 0         ┆ 0                   ┆ 0     ┆ 0             │
└──────────┴───────────────┴────────────┴───────────┴─────────────────────┴───────┴───────────────┘

In [33]:
order_items = order_items.with_columns(
    pl.col("shipping_limit_date").str.to_datetime("%Y-%m-%d %H:%M:%S")
)

This seems like an intermediate table, that would be useful in the data agreggation within the gold layer.

In [34]:
order_items.head()

shape: (5, 7)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────┬──────────────┐
│ order_id      ┆ order_item_i ┆ product_id   ┆ seller_id    ┆ shipping_lim ┆ price ┆ freight_valu │
│ ---           ┆ d            ┆ ---          ┆ ---          ┆ it_date      ┆ ---   ┆ e            │
│ str           ┆ ---          ┆ str          ┆ str          ┆ ---          ┆ f64   ┆ ---          │
│               ┆ i64          ┆              ┆              ┆ datetime[μs] ┆       ┆ f64          │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════╪══════════════╡
│ 00010242fe8c5 ┆ 1            ┆ 4244733e06e7 ┆ 48436dade18a ┆ 2017-09-19   ┆ 58.9  ┆ 13.29        │
│ a6d1ba2dd792c ┆              ┆ ecb4970a6e26 ┆ c8b2bce089ec ┆ 09:45:35     ┆       ┆              │
│ b162…         ┆              ┆ 83c13e…      ┆ 2a0412…      ┆              ┆       ┆              │
│ 00018f77f2f03 ┆ 1            ┆ e5f2d52b8021 ┆ dd7ddc04e1b6 ┆ 2017-05-03   ┆ 239.9 ┆ 19.93        │
│ 20c557190d7a1 ┆              ┆ 89ee658865ca ┆ c2c614352b38 ┆ 11:05:13     ┆       ┆              │
│ 44bd…         ┆              ┆ 93d83a…      ┆ 3efe2d…      ┆              ┆       ┆              │
│ 000229ec39822 ┆ 1            ┆ c777355d18b7 ┆ 5b51032eddd2 ┆ 2018-01-18   ┆ 199.0 ┆ 17.87        │
│ 4ef6ca0657da4 ┆              ┆ 2b67abbeef9d ┆ 42adc84c38ac ┆ 14:48:30     ┆       ┆              │
│ fc70…         ┆              ┆ f44fd0…      ┆ ab88f2…      ┆              ┆       ┆              │
│ 00024acbcdf0a ┆ 1            ┆ 7634da152a46 ┆ 9d7a1d34a505 ┆ 2018-08-15   ┆ 12.99 ┆ 12.79        │
│ 6daa1e931b038 ┆              ┆ 10f1595efa32 ┆ 240900642527 ┆ 10:10:18     ┆       ┆              │
│ 114c…         ┆              ┆ f14722…      ┆ 5ba1c2…      ┆              ┆       ┆              │
│ 00042b26cf59d ┆ 1            ┆ ac6c3623068f ┆ df560393f3a5 ┆ 2017-02-13   ┆ 199.9 ┆ 18.14        │
│ 7ce69dfabb4e5 ┆              ┆ 30de03045865 ┆ 1e74553ab940 ┆ 13:57:51     ┆       ┆              │
│ 5b4f…         ┆              ┆ e4e100…      ┆ 04ba5c…      ┆              ┆       ┆              │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────┴──────────────┘

### Order payments

A good sanity check can be to verify that the order sum from order payments matches the price in the order_items & orders tables!

In [30]:
order_payments.head()

shape: (5, 5)
┌───────────────────────┬────────────────────┬──────────────┬──────────────────────┬───────────────┐
│ order_id              ┆ payment_sequential ┆ payment_type ┆ payment_installments ┆ payment_value │
│ ---                   ┆ ---                ┆ ---          ┆ ---                  ┆ ---           │
│ str                   ┆ i64                ┆ str          ┆ i64                  ┆ f64           │
╞═══════════════════════╪════════════════════╪══════════════╪══════════════════════╪═══════════════╡
│ b81ef226f3fe1789b1e8b ┆ 1                  ┆ credit_card  ┆ 8                    ┆ 99.33         │
│ 2acac839d…            ┆                    ┆              ┆                      ┆               │
│ a9810da82917af2d9aefd ┆ 1                  ┆ credit_card  ┆ 1                    ┆ 24.39         │
│ 1278f1dcf…            ┆                    ┆              ┆                      ┆               │
│ 25e8ea4e93396b6fa0d3d ┆ 1                  ┆ credit_card  ┆ 1                    ┆ 65.71         │
│ d708e76c1…            ┆                    ┆              ┆                      ┆               │
│ ba78997921bbcdc1373bb ┆ 1                  ┆ credit_card  ┆ 8                    ┆ 107.78        │
│ 41e913ab9…            ┆                    ┆              ┆                      ┆               │
│ 42fdf880ba16b47b59251 ┆ 1                  ┆ credit_card  ┆ 2                    ┆ 128.45        │
│ dd489d444…            ┆                    ┆              ┆                      ┆               │
└───────────────────────┴────────────────────┴──────────────┴──────────────────────┴───────────────┘

In [31]:
order_payments.null_count()

shape: (1, 5)
┌──────────┬────────────────────┬──────────────┬──────────────────────┬───────────────┐
│ order_id ┆ payment_sequential ┆ payment_type ┆ payment_installments ┆ payment_value │
│ ---      ┆ ---                ┆ ---          ┆ ---                  ┆ ---           │
│ u32      ┆ u32                ┆ u32          ┆ u32                  ┆ u32           │
╞══════════╪════════════════════╪══════════════╪══════════════════════╪═══════════════╡
│ 0        ┆ 0                  ┆ 0            ┆ 0                    ┆ 0             │
└──────────┴────────────────────┴──────────────┴──────────────────────┴───────────────┘

In [38]:
order_payments.filter(pl.col("payment_sequential") > 5).sort('payment_sequential', descending=True)

shape: (458, 5)
┌───────────────────────┬────────────────────┬──────────────┬──────────────────────┬───────────────┐
│ order_id              ┆ payment_sequential ┆ payment_type ┆ payment_installments ┆ payment_value │
│ ---                   ┆ ---                ┆ ---          ┆ ---                  ┆ ---           │
│ str                   ┆ i64                ┆ str          ┆ i64                  ┆ f64           │
╞═══════════════════════╪════════════════════╪══════════════╪══════════════════════╪═══════════════╡
│ fa65dad1b0e818e3ccc5c ┆ 29                 ┆ voucher      ┆ 1                    ┆ 19.26         │
│ b0e392313…            ┆                    ┆              ┆                      ┆               │
│ fa65dad1b0e818e3ccc5c ┆ 28                 ┆ voucher      ┆ 1                    ┆ 29.05         │
│ b0e392313…            ┆                    ┆              ┆                      ┆               │
│ fa65dad1b0e818e3ccc5c ┆ 27                 ┆ voucher      ┆ 1                    ┆ 66.02         │
│ b0e392313…            ┆                    ┆              ┆                      ┆               │
│ ccf804e764ed5650cd875 ┆ 26                 ┆ voucher      ┆ 1                    ┆ 23.1          │
│ 9557269dc…            ┆                    ┆              ┆                      ┆               │
│ fa65dad1b0e818e3ccc5c ┆ 26                 ┆ voucher      ┆ 1                    ┆ 28.27         │
│ b0e392313…            ┆                    ┆              ┆                      ┆               │
│ …                     ┆ …                  ┆ …            ┆ …                    ┆ …             │
│ 27a940efdd448db29463b ┆ 6                  ┆ voucher      ┆ 1                    ┆ 4.17          │
│ 53ea0cfa2…            ┆                    ┆              ┆                      ┆               │
│ 4f53648717b48854fb9db ┆ 6                  ┆ voucher      ┆ 1                    ┆ 4.74          │
│ 283e2cf5d…            ┆                    ┆              ┆                      ┆               │
│ 465c2e1bee4561cb39e0d ┆ 6                  ┆ voucher      ┆ 1                    ┆ 13.4          │
│ b8c5993aa…            ┆                    ┆              ┆                      ┆               │
│ fedcd9f7ccdc8cba3a18d ┆ 6                  ┆ voucher      ┆ 1                    ┆ 8.6           │
│ efedd1a55…            ┆                    ┆              ┆                      ┆               │
│ 31bc09fdbd701a7a4f9b5 ┆ 6                  ┆ voucher      ┆ 1                    ┆ 77.99         │
│ 5b5955b86…            ┆                    ┆              ┆                      ┆               │
└───────────────────────┴────────────────────┴──────────────┴──────────────────────┴───────────────┘

### Order reviews

Pre-processing: drop the review title and the review comment messages, and convert the timestamp data.

In [39]:
order_reviews.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ review_id    ┆ order_id    ┆ review_scor ┆ review_comm ┆ review_comm ┆ review_crea ┆ review_answ │
│ ---          ┆ ---         ┆ e           ┆ ent_title   ┆ ent_message ┆ tion_date   ┆ er_timestam │
│ str          ┆ str         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ p           │
│              ┆             ┆ i64         ┆ str         ┆ str         ┆ str         ┆ ---         │
│              ┆             ┆             ┆             ┆             ┆             ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 7bc2406110b9 ┆ 73fc7af8711 ┆ 4           ┆ null        ┆ null        ┆ 2018-01-18  ┆ 2018-01-18  │
│ 26393aa56f80 ┆ 4b39712e6da ┆             ┆             ┆             ┆ 00:00:00    ┆ 21:46:59    │
│ a40eba…      ┆ 79b0a377…   ┆             ┆             ┆             ┆             ┆             │
│ 80e641a11e56 ┆ a548910a1c6 ┆ 5           ┆ null        ┆ null        ┆ 2018-03-10  ┆ 2018-03-11  │
│ f04c1ad469d5 ┆ 147796b98fd ┆             ┆             ┆             ┆ 00:00:00    ┆ 03:05:13    │
│ 645fdf…      ┆ f73dbeba…   ┆             ┆             ┆             ┆             ┆             │
│ 228ce5500dc1 ┆ f9e4b658b20 ┆ 5           ┆ null        ┆ null        ┆ 2018-02-17  ┆ 2018-02-18  │
│ d8e020d8d132 ┆ 1a9f2ecdecb ┆             ┆             ┆             ┆ 00:00:00    ┆ 14:36:24    │
│ 2874b6…      ┆ b34bed03…   ┆             ┆             ┆             ┆             ┆             │
│ e64fb393e7b3 ┆ 658677c97b3 ┆ 5           ┆ null        ┆ Recebi bem  ┆ 2017-04-21  ┆ 2017-04-21  │
│ 2834bb789ff8 ┆ 85a9be17073 ┆             ┆             ┆ antes do    ┆ 00:00:00    ┆ 22:02:06    │
│ bb3075…      ┆ 7859d351…   ┆             ┆             ┆ prazo esti… ┆             ┆             │
│ f7c4243c7fe1 ┆ 8e6bfb81e28 ┆ 5           ┆ null        ┆ Parabéns    ┆ 2018-03-01  ┆ 2018-03-02  │
│ 938f181bec41 ┆ 3fa7e4f1112 ┆             ┆             ┆ lojas       ┆ 00:00:00    ┆ 10:26:53    │
│ a392bd…      ┆ 3a3fb894…   ┆             ┆             ┆ lannister   ┆             ┆             │
│              ┆             ┆             ┆             ┆ adore…      ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [40]:
order_reviews['review_id'].is_unique().all()

False

Interestingly not all review id's are completely unique

In [43]:
order_reviews.null_count() / order_reviews.height

shape: (1, 7)
┌───────────┬──────────┬──────────────┬───────────────┬──────────────┬──────────────┬──────────────┐
│ review_id ┆ order_id ┆ review_score ┆ review_commen ┆ review_comme ┆ review_creat ┆ review_answe │
│ ---       ┆ ---      ┆ ---          ┆ t_title       ┆ nt_message   ┆ ion_date     ┆ r_timestamp  │
│ f64       ┆ f64      ┆ f64          ┆ ---           ┆ ---          ┆ ---          ┆ ---          │
│           ┆          ┆              ┆ f64           ┆ f64          ┆ f64          ┆ f64          │
╞═══════════╪══════════╪══════════════╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ 0.0       ┆ 0.0      ┆ 0.0          ┆ 0.883415      ┆ 0.587025     ┆ 0.0          ┆ 0.0          │
└───────────┴──────────┴──────────────┴───────────────┴──────────────┴──────────────┴──────────────┘

More than 50% of the data is missing for the review text columns. Since we are not concerned with NLP we will drop those columns. We will also convert timestamp data into timestamp format.

In [44]:
order_reviews = (
    order_reviews
    .drop(["review_comment_title", "review_comment_message"])
    .with_columns(
        pl.col("review_creation_date").str.to_datetime("%Y-%m-%d %H:%M:%S"),
        pl.col("review_answer_timestamp").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    )
)
order_reviews

shape: (99_224, 5)
┌────────────────────┬────────────────────┬──────────────┬────────────────────┬────────────────────┐
│ review_id          ┆ order_id           ┆ review_score ┆ review_creation_da ┆ review_answer_time │
│ ---                ┆ ---                ┆ ---          ┆ te                 ┆ stamp              │
│ str                ┆ str                ┆ i64          ┆ ---                ┆ ---                │
│                    ┆                    ┆              ┆ datetime[μs]       ┆ datetime[μs]       │
╞════════════════════╪════════════════════╪══════════════╪════════════════════╪════════════════════╡
│ 7bc2406110b926393a ┆ 73fc7af87114b39712 ┆ 4            ┆ 2018-01-18         ┆ 2018-01-18         │
│ a56f80a40eba…      ┆ e6da79b0a377…      ┆              ┆ 00:00:00           ┆ 21:46:59           │
│ 80e641a11e56f04c1a ┆ a548910a1c6147796b ┆ 5            ┆ 2018-03-10         ┆ 2018-03-11         │
│ d469d5645fdf…      ┆ 98fdf73dbeba…      ┆              ┆ 00:00:00           ┆ 03:05:13           │
│ 228ce5500dc1d8e020 ┆ f9e4b658b201a9f2ec ┆ 5            ┆ 2018-02-17         ┆ 2018-02-18         │
│ d8d1322874b6…      ┆ decbb34bed03…      ┆              ┆ 00:00:00           ┆ 14:36:24           │
│ e64fb393e7b32834bb ┆ 658677c97b385a9be1 ┆ 5            ┆ 2017-04-21         ┆ 2017-04-21         │
│ 789ff8bb3075…      ┆ 70737859d351…      ┆              ┆ 00:00:00           ┆ 22:02:06           │
│ f7c4243c7fe1938f18 ┆ 8e6bfb81e283fa7e4f ┆ 5            ┆ 2018-03-01         ┆ 2018-03-02         │
│ 1bec41a392bd…      ┆ 11123a3fb894…      ┆              ┆ 00:00:00           ┆ 10:26:53           │
│ …                  ┆ …                  ┆ …            ┆ …                  ┆ …                  │
│ 574ed12dd733e5fa53 ┆ 2a8c23fee101d4d566 ┆ 5            ┆ 2018-07-07         ┆ 2018-07-14         │
│ 0cfd4bbf39d7…      ┆ 2fa670396eb8…      ┆              ┆ 00:00:00           ┆ 17:18:30           │
│ f3897127253a9592a7 ┆ 22ec9f0669f784db00 ┆ 5            ┆ 2017-12-09         ┆ 2017-12-11         │
│ 3be9bdfdf4ed…      ┆ fa86d035cf86…      ┆              ┆ 00:00:00           ┆ 20:06:42           │
│ b3de70c89b1510c4cd ┆ 55d4004744368f5571 ┆ 5            ┆ 2018-03-22         ┆ 2018-03-23         │
│ 3d0649fd3024…      ┆ d1f590031933…      ┆              ┆ 00:00:00           ┆ 09:10:43           │
│ 1adeb9d84d72fe4e33 ┆ 7725825d039fc1f0ce ┆ 4            ┆ 2018-07-01         ┆ 2018-07-02         │
│ 7617733eb851…      ┆ b7635e3f7d92…      ┆              ┆ 00:00:00           ┆ 12:59:13           │
│ efe49f1d6f951dd88b ┆ 90531360ecb1eec2a1 ┆ 1            ┆ 2017-07-03         ┆ 2017-07-03         │
│ 51e6ccd4cc54…      ┆ fbb265a0db05…      ┆              ┆ 00:00:00           ┆ 21:01:49           │
└────────────────────┴────────────────────┴──────────────┴────────────────────┴────────────────────┘

In [48]:
order_reviews.filter(order_reviews['review_id'].is_unique() == False).sort('review_id')

shape: (1_603, 5)
┌────────────────────┬────────────────────┬──────────────┬────────────────────┬────────────────────┐
│ review_id          ┆ order_id           ┆ review_score ┆ review_creation_da ┆ review_answer_time │
│ ---                ┆ ---                ┆ ---          ┆ te                 ┆ stamp              │
│ str                ┆ str                ┆ i64          ┆ ---                ┆ ---                │
│                    ┆                    ┆              ┆ datetime[μs]       ┆ datetime[μs]       │
╞════════════════════╪════════════════════╪══════════════╪════════════════════╪════════════════════╡
│ 00130cbe1f9d422698 ┆ 04a28263e085d399c9 ┆ 1            ┆ 2018-03-07         ┆ 2018-03-20         │
│ c812ed8ded19…      ┆ 7ae49e0b477e…      ┆              ┆ 00:00:00           ┆ 18:08:23           │
│ 00130cbe1f9d422698 ┆ dfcdfc43867d1c1381 ┆ 1            ┆ 2018-03-07         ┆ 2018-03-20         │
│ c812ed8ded19…      ┆ bfaf62d6b9c1…      ┆              ┆ 00:00:00           ┆ 18:08:23           │
│ 0115633a9c298b6a98 ┆ 0c9850b2c179c1ef60 ┆ 5            ┆ 2017-09-21         ┆ 2017-09-26         │
│ bcbe4eee7534…      ┆ d2855e2751d1…      ┆              ┆ 00:00:00           ┆ 03:27:47           │
│ 0115633a9c298b6a98 ┆ 78a4201f58af3463bd ┆ 5            ┆ 2017-09-21         ┆ 2017-09-26         │
│ bcbe4eee7534…      ┆ ab842eea4bc8…      ┆              ┆ 00:00:00           ┆ 03:27:47           │
│ 0174caf0ee59646460 ┆ 74db91e33b4e1fd865 ┆ 1            ┆ 2018-03-07         ┆ 2018-03-08         │
│ 40cd94e15ac9…      ┆ 356c89a61abf…      ┆              ┆ 00:00:00           ┆ 03:00:53           │
│ …                  ┆ …                  ┆ …            ┆ …                  ┆ …                  │
│ fe5c833752953fed32 ┆ d3775e436e60258e62 ┆ 1            ┆ 2018-02-28         ┆ 2018-02-28         │
│ 09646f1f63b5…      ┆ e678a0f68a0f…      ┆              ┆ 00:00:00           ┆ 13:57:52           │
│ ff2fc9e68f8aabfbe1 ┆ 2da58e0a7dcfa4ce1e ┆ 2            ┆ 2018-03-17         ┆ 2018-03-19         │
│ 8d710b83aabd…      ┆ 00fad9d03ca3…      ┆              ┆ 00:00:00           ┆ 11:44:15           │
│ ff2fc9e68f8aabfbe1 ┆ 1078d496cc6ab9a8e6 ┆ 2            ┆ 2018-03-17         ┆ 2018-03-19         │
│ 8d710b83aabd…      ┆ f2be77abf509…      ┆              ┆ 00:00:00           ┆ 11:44:15           │
│ ffb8cff872a625632a ┆ c88b1d1b157a9999ce ┆ 3            ┆ 2017-07-22         ┆ 2017-07-26         │
│ c983eb1f8884…      ┆ 368f218a4071…      ┆              ┆ 00:00:00           ┆ 13:41:07           │
│ ffb8cff872a625632a ┆ c44883fc2529b4aa03 ┆ 3            ┆ 2017-07-22         ┆ 2017-07-26         │
│ c983eb1f8884…      ┆ ca90e7e09d95…      ┆              ┆ 00:00:00           ┆ 13:41:07           │
└────────────────────┴────────────────────┴──────────────┴────────────────────┴────────────────────┘

Same review can occur for multiple orders! When joining this dataset it is better to use review_id + order_id as a composite key.

### Orders

Pre processing: conversion of the timestamp data to proper type.

In [50]:
orders.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_stat ┆ order_pur ┆ order_app ┆ order_del ┆ order_del ┆ order_est │
│ ---        ┆ d          ┆ us         ┆ chase_tim ┆ roved_at  ┆ ivered_ca ┆ ivered_cu ┆ imated_de │
│ str        ┆ ---        ┆ ---        ┆ estamp    ┆ ---       ┆ rrier_dat ┆ stomer_da ┆ livery_da │
│            ┆ str        ┆ str        ┆ ---       ┆ str       ┆ e         ┆ te        ┆ te        │
│            ┆            ┆            ┆ str       ┆           ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ e481f51cbd ┆ 9ef432eb62 ┆ delivered  ┆ 2017-10-0 ┆ 2017-10-0 ┆ 2017-10-0 ┆ 2017-10-1 ┆ 2017-10-1 │
│ c54678b7cc ┆ 51297304e7 ┆            ┆ 2         ┆ 2         ┆ 4         ┆ 0         ┆ 8         │
│ 49136f2d6a ┆ 6186b10a92 ┆            ┆ 10:56:33  ┆ 11:07:15  ┆ 19:55:00  ┆ 21:25:13  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 53cdb2fc8b ┆ b0830fb474 ┆ delivered  ┆ 2018-07-2 ┆ 2018-07-2 ┆ 2018-07-2 ┆ 2018-08-0 ┆ 2018-08-1 │
│ c7dce0b674 ┆ 7a6c6d20de ┆            ┆ 4         ┆ 6         ┆ 6         ┆ 7         ┆ 3         │
│ 1e21502734 ┆ a0b8c802d7 ┆            ┆ 20:41:37  ┆ 03:24:27  ┆ 14:31:00  ┆ 15:27:45  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 47770eb910 ┆ 41ce2a54c0 ┆ delivered  ┆ 2018-08-0 ┆ 2018-08-0 ┆ 2018-08-0 ┆ 2018-08-1 ┆ 2018-09-0 │
│ 0c2d0c4494 ┆ b03bf3443c ┆            ┆ 8         ┆ 8         ┆ 8         ┆ 7         ┆ 4         │
│ 6d9cf07ec6 ┆ 3d931a3670 ┆            ┆ 08:38:49  ┆ 08:55:23  ┆ 13:50:00  ┆ 18:06:29  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 949d5b44db ┆ f88197465e ┆ delivered  ┆ 2017-11-1 ┆ 2017-11-1 ┆ 2017-11-2 ┆ 2017-12-0 ┆ 2017-12-1 │
│ f5de918fe9 ┆ a7920adcdb ┆            ┆ 8         ┆ 8         ┆ 2         ┆ 2         ┆ 5         │
│ c16f97b45f ┆ ec7375364d ┆            ┆ 19:28:06  ┆ 19:45:59  ┆ 13:39:59  ┆ 00:28:42  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ ad21c59c08 ┆ 8ab97904e6 ┆ delivered  ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-2 │
│ 40e6cb83a9 ┆ daea8866db ┆            ┆ 3         ┆ 3         ┆ 4         ┆ 6         ┆ 6         │
│ ceb5573f81 ┆ dbc4fb7aad ┆            ┆ 21:18:39  ┆ 22:20:29  ┆ 19:46:34  ┆ 18:17:02  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

Order id and customer id are both unique columns

In [51]:
orders["order_id"].is_unique().all() and orders["customer_id"].is_unique().all()

True

There are however some missing values for carrier date and customer date. The delivery pipeline works as follows: 

purchased → payment approved → handed to carrier → delivered to customer → (compared against) estimated delivery date

Missing values are thus informative of underperformance that could be the culprit for the seller under-performance, lowering the sales volume.

If the carrier date is null, then that means that the seller never handed off the delivery to the carrier, while the customer date null means that the order was never delivered to the customer.

In [54]:
orders.filter(pl.col("order_delivered_customer_date").is_null()).select(['order_delivered_carrier_date', 'order_delivered_customer_date'])

shape: (2_965, 2)
┌──────────────────────────────┬───────────────────────────────┐
│ order_delivered_carrier_date ┆ order_delivered_customer_date │
│ ---                          ┆ ---                           │
│ str                          ┆ str                           │
╞══════════════════════════════╪═══════════════════════════════╡
│ null                         ┆ null                          │
│ 2018-06-05 14:32:00          ┆ null                          │
│ null                         ┆ null                          │
│ null                         ┆ null                          │
│ 2018-01-11 19:39:23          ┆ null                          │
│ …                            ┆ …                             │
│ null                         ┆ null                          │
│ null                         ┆ null                          │
│ null                         ┆ null                          │
│ null                         ┆ null                          │
│ null                         ┆ null                          │
└──────────────────────────────┴───────────────────────────────┘

In [56]:
orders.filter(
    pl.col("order_delivered_carrier_date").is_null()
    & pl.col("order_delivered_customer_date").is_not_null()
)

shape: (1, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_stat ┆ order_pur ┆ order_app ┆ order_del ┆ order_del ┆ order_est │
│ ---        ┆ d          ┆ us         ┆ chase_tim ┆ roved_at  ┆ ivered_ca ┆ ivered_cu ┆ imated_de │
│ str        ┆ ---        ┆ ---        ┆ estamp    ┆ ---       ┆ rrier_dat ┆ stomer_da ┆ livery_da │
│            ┆ str        ┆ str        ┆ ---       ┆ str       ┆ e         ┆ te        ┆ te        │
│            ┆            ┆            ┆ str       ┆           ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2aa9110885 ┆ afeb16c7f4 ┆ delivered  ┆ 2017-09-2 ┆ 2017-09-2 ┆ null      ┆ 2017-11-2 ┆ 2017-11-1 │
│ 3cecb43c84 ┆ 6396c0ed54 ┆            ┆ 9         ┆ 9         ┆           ┆ 0         ┆ 4         │
│ a5dc5b2774 ┆ acb45ccaaa ┆            ┆ 08:52:58  ┆ 09:07:16  ┆           ┆ 19:44:47  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

Majority of the orders are handled through a carrier, although a single case shows a situation where the order was delivered directly to the customer, bypassing the carrier.

There could be several explanations:

Either the seller delivered the item directly, or this is a logging error. 

In any case a single row will not move meaningfully any aggregate metric, although it is useful to be aware about potential issues.

In [58]:
orders.group_by("order_status").agg(
    pl.col("order_delivered_carrier_date").null_count().alias("carrier_nulls"),
    pl.col("order_delivered_customer_date").null_count().alias("customer_nulls"),
    pl.len().alias("total"),
)

shape: (8, 4)
┌──────────────┬───────────────┬────────────────┬───────┐
│ order_status ┆ carrier_nulls ┆ customer_nulls ┆ total │
│ ---          ┆ ---           ┆ ---            ┆ ---   │
│ str          ┆ u32           ┆ u32            ┆ u32   │
╞══════════════╪═══════════════╪════════════════╪═══════╡
│ unavailable  ┆ 609           ┆ 609            ┆ 609   │
│ delivered    ┆ 2             ┆ 8              ┆ 96478 │
│ processing   ┆ 301           ┆ 301            ┆ 301   │
│ created      ┆ 5             ┆ 5              ┆ 5     │
│ approved     ┆ 2             ┆ 2              ┆ 2     │
│ invoiced     ┆ 314           ┆ 314            ┆ 314   │
│ shipped      ┆ 0             ┆ 1107           ┆ 1107  │
│ canceled     ┆ 550           ┆ 619            ┆ 625   │
└──────────────┴───────────────┴────────────────┴───────┘

We have some minor inconsistencies, which are probably just logging errors, they will not meaningfully affect the results. In general cases the null values are representative - e.g if the order is shipped, it should hot have a customer delivery date.

In [59]:
orders = orders.with_columns(
    pl.col("order_purchase_timestamp").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("order_approved_at").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("order_delivered_carrier_date").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("order_delivered_customer_date").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("order_estimated_delivery_date").str.to_datetime("%Y-%m-%d %H:%M:%S"),
)

In [60]:
orders.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_stat ┆ order_pur ┆ order_app ┆ order_del ┆ order_del ┆ order_est │
│ ---        ┆ d          ┆ us         ┆ chase_tim ┆ roved_at  ┆ ivered_ca ┆ ivered_cu ┆ imated_de │
│ str        ┆ ---        ┆ ---        ┆ estamp    ┆ ---       ┆ rrier_dat ┆ stomer_da ┆ livery_da │
│            ┆ str        ┆ str        ┆ ---       ┆ datetime[ ┆ e         ┆ te        ┆ te        │
│            ┆            ┆            ┆ datetime[ ┆ μs]       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆ μs]       ┆           ┆ datetime[ ┆ datetime[ ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆ μs]       ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ e481f51cbd ┆ 9ef432eb62 ┆ delivered  ┆ 2017-10-0 ┆ 2017-10-0 ┆ 2017-10-0 ┆ 2017-10-1 ┆ 2017-10-1 │
│ c54678b7cc ┆ 51297304e7 ┆            ┆ 2         ┆ 2         ┆ 4         ┆ 0         ┆ 8         │
│ 49136f2d6a ┆ 6186b10a92 ┆            ┆ 10:56:33  ┆ 11:07:15  ┆ 19:55:00  ┆ 21:25:13  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 53cdb2fc8b ┆ b0830fb474 ┆ delivered  ┆ 2018-07-2 ┆ 2018-07-2 ┆ 2018-07-2 ┆ 2018-08-0 ┆ 2018-08-1 │
│ c7dce0b674 ┆ 7a6c6d20de ┆            ┆ 4         ┆ 6         ┆ 6         ┆ 7         ┆ 3         │
│ 1e21502734 ┆ a0b8c802d7 ┆            ┆ 20:41:37  ┆ 03:24:27  ┆ 14:31:00  ┆ 15:27:45  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 47770eb910 ┆ 41ce2a54c0 ┆ delivered  ┆ 2018-08-0 ┆ 2018-08-0 ┆ 2018-08-0 ┆ 2018-08-1 ┆ 2018-09-0 │
│ 0c2d0c4494 ┆ b03bf3443c ┆            ┆ 8         ┆ 8         ┆ 8         ┆ 7         ┆ 4         │
│ 6d9cf07ec6 ┆ 3d931a3670 ┆            ┆ 08:38:49  ┆ 08:55:23  ┆ 13:50:00  ┆ 18:06:29  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 949d5b44db ┆ f88197465e ┆ delivered  ┆ 2017-11-1 ┆ 2017-11-1 ┆ 2017-11-2 ┆ 2017-12-0 ┆ 2017-12-1 │
│ f5de918fe9 ┆ a7920adcdb ┆            ┆ 8         ┆ 8         ┆ 2         ┆ 2         ┆ 5         │
│ c16f97b45f ┆ ec7375364d ┆            ┆ 19:28:06  ┆ 19:45:59  ┆ 13:39:59  ┆ 00:28:42  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ ad21c59c08 ┆ 8ab97904e6 ┆ delivered  ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-2 │
│ 40e6cb83a9 ┆ daea8866db ┆            ┆ 3         ┆ 3         ┆ 4         ┆ 6         ┆ 6         │
│ ceb5573f81 ┆ dbc4fb7aad ┆            ┆ 21:18:39  ┆ 22:20:29  ┆ 19:46:34  ┆ 18:17:02  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

### Products

For the products category in the gold layer it might be better to swap the category names to the english version.

In [61]:
products.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ product_i ┆ product_c ┆ product_n ┆ product_d ┆ … ┆ product_w ┆ product_l ┆ product_h ┆ product_ │
│ d         ┆ ategory_n ┆ ame_lengh ┆ escriptio ┆   ┆ eight_g   ┆ ength_cm  ┆ eight_cm  ┆ width_cm │
│ ---       ┆ ame       ┆ t         ┆ n_lenght  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆ str       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1e9e8ef04 ┆ perfumari ┆ 40.0      ┆ 287.0     ┆ … ┆ 225.0     ┆ 16.0      ┆ 10.0      ┆ 14.0     │
│ dbcff4541 ┆ a         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ed26657ea ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 517…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3aa071139 ┆ artes     ┆ 44.0      ┆ 276.0     ┆ … ┆ 1000.0    ┆ 30.0      ┆ 18.0      ┆ 20.0     │
│ cb16b67ca ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9e5dea641 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aaa…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 96bd76ec8 ┆ esporte_l ┆ 46.0      ┆ 250.0     ┆ … ┆ 154.0     ┆ 18.0      ┆ 9.0       ┆ 15.0     │
│ 810374ed1 ┆ azer      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b65e29197 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 571…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cef67bcfe ┆ bebes     ┆ 27.0      ┆ 261.0     ┆ … ┆ 371.0     ┆ 26.0      ┆ 4.0       ┆ 26.0     │
│ 19066a932 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b7673e239 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ eb2…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9dc1a7de2 ┆ utilidade ┆ 37.0      ┆ 402.0     ┆ … ┆ 625.0     ┆ 20.0      ┆ 17.0      ┆ 13.0     │
│ 74444849c ┆ s_domesti ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 219cff195 ┆ cas       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d0b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [63]:
products.filter(pl.col('product_category_name').is_null())

shape: (610, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ product_i ┆ product_c ┆ product_n ┆ product_d ┆ … ┆ product_w ┆ product_l ┆ product_h ┆ product_ │
│ d         ┆ ategory_n ┆ ame_lengh ┆ escriptio ┆   ┆ eight_g   ┆ ength_cm  ┆ eight_cm  ┆ width_cm │
│ ---       ┆ ame       ┆ t         ┆ n_lenght  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆ str       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a41e356c7 ┆ null      ┆ null      ┆ null      ┆ … ┆ 650.0     ┆ 17.0      ┆ 14.0      ┆ 12.0     │
│ 6fab66334 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f36de622e ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cbd…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d8dee61c2 ┆ null      ┆ null      ┆ null      ┆ … ┆ 300.0     ┆ 16.0      ┆ 7.0       ┆ 20.0     │
│ 034d6d075 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 997acef18 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 70e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 56139431d ┆ null      ┆ null      ┆ null      ┆ … ┆ 200.0     ┆ 20.0      ┆ 20.0      ┆ 20.0     │
│ 72cd51f19 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ eb9f7dae4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d16…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 46b48281e ┆ null      ┆ null      ┆ null      ┆ … ┆ 18500.0   ┆ 41.0      ┆ 30.0      ┆ 41.0     │
│ b6d663ced ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 748f32410 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8c7…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5fb61f482 ┆ null      ┆ null      ┆ null      ┆ … ┆ 300.0     ┆ 35.0      ┆ 7.0       ┆ 12.0     │
│ 620cb672f ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5e586bb13 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2ea…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ b0a0c5dd7 ┆ null      ┆ null      ┆ null      ┆ … ┆ 1800.0    ┆ 30.0      ┆ 20.0      ┆ 70.0     │
│ 8e644373b ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 199380612 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c35…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10dbe0fba ┆ null      ┆ null      ┆ null      ┆ … ┆ 800.0     ┆ 30.0      ┆ 10.0      ┆ 23.0     │
│ a2c505123 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c17fdc34a ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 63c…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ bd2ada37b ┆ null      ┆ null      ┆ null      ┆ … ┆ 200.0     ┆ 21.0      ┆ 8.0       ┆ 16.0     │
│ 58ae94cc8 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 38b9c0569 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ fec…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ fa51e9140 ┆ null      ┆ null      ┆ null      ┆ … ┆ 1300.0    ┆ 45.0      ┆ 16.0      ┆ 45.0     │
│ 46aab3276 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4c41356b9 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d4e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4ceee876 ┆ null      ┆ null      ┆ null      ┆ … ┆ 700.0     ┆ 28.0      ┆ 3.0       ┆ 43.0     │
│ c82b8328e ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9c293fa0e ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 198…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [65]:
products.null_count() / products.height

shape: (1, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ product_i ┆ product_c ┆ product_n ┆ product_d ┆ … ┆ product_w ┆ product_l ┆ product_h ┆ product_ │
│ d         ┆ ategory_n ┆ ame_lengh ┆ escriptio ┆   ┆ eight_g   ┆ ength_cm  ┆ eight_cm  ┆ width_cm │
│ ---       ┆ ame       ┆ t         ┆ n_lenght  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0       ┆ 0.018512  ┆ 0.018512  ┆ 0.018512  ┆ … ┆ 0.000061  ┆ 0.000061  ┆ 0.000061  ┆ 0.000061 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Even though we could drop the nulls for the product category name, the unique product_id's might come in handy when joining the tables. We will leave them in the pre processing pipeline.

### Sellers

No preprocesssing required here.

In [64]:
sellers.head()

shape: (5, 4)
┌─────────────────────────────────┬────────────────────────┬───────────────────┬──────────────┐
│ seller_id                       ┆ seller_zip_code_prefix ┆ seller_city       ┆ seller_state │
│ ---                             ┆ ---                    ┆ ---               ┆ ---          │
│ str                             ┆ i64                    ┆ str               ┆ str          │
╞═════════════════════════════════╪════════════════════════╪═══════════════════╪══════════════╡
│ 3442f8959a84dea7ee197c632cb2df… ┆ 13023                  ┆ campinas          ┆ SP           │
│ d1b65fc7debc3361ea86b5f14c68d2… ┆ 13844                  ┆ mogi guacu        ┆ SP           │
│ ce3ad9de960102d0677a81f5d0bb7b… ┆ 20031                  ┆ rio de janeiro    ┆ RJ           │
│ c0f3eea2e14555b6faeea3dd58c1b1… ┆ 4195                   ┆ sao paulo         ┆ SP           │
│ 51a04a8a6bdcb23deccc82b0b80742… ┆ 12914                  ┆ braganca paulista ┆ SP           │
└─────────────────────────────────┴────────────────────────┴───────────────────┴──────────────┘

### Category translation

No preprocessing required here

In [62]:
category_translation.head()

shape: (5, 2)
┌────────────────────────┬───────────────────────────────┐
│ product_category_name  ┆ product_category_name_english │
│ ---                    ┆ ---                           │
│ str                    ┆ str                           │
╞════════════════════════╪═══════════════════════════════╡
│ beleza_saude           ┆ health_beauty                 │
│ informatica_acessorios ┆ computers_accessories         │
│ automotivo             ┆ auto                          │
│ cama_mesa_banho        ┆ bed_bath_table                │
│ moveis_decoracao       ┆ furniture_decor               │
└────────────────────────┴───────────────────────────────┘

## Pre processing verification

In [ ]:
customers_cleaned            = customers
geolocation_cleaned          = geolocation
order_items_cleaned          = order_items
order_payments_cleaned       = order_payments
order_reviews_cleaned        = order_reviews
orders_cleaned               = orders
products_cleaned             = products
sellers_cleaned              = sellers
category_translation_cleaned = category_translation

## Silver to Gold - Reshaping the data for business analysis (Power BI)

Core idea of this layer: remove data redundancy and reshape the data into a star schema to support the business analysis.